#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    if getent passwd router_controller >/dev/null; then
        deluser --system router_controller || true
    fi

    if getent group router_controller >/dev/null; then
        delgroup --system router_controller || true
    fi

    rm -rf /var/lib/router-pi-controller
fi

exit 0